nfs-service:
	image: busybox
	command: /bin/true
	net: none
	volumes:
		- /var/run
		- /var/lib/glusterd
		- ${HOST_MOUNT}/data/glusterfs/brick1
	labels:
		io.rancher.container.hostname_override: container_name