name: "NFS Storage" # Name of the Catalog Entry
description: |
  NFS Storage based on alpine # Description of the Catalog Entry
version: "0.1.0" # Version of the Catalog to be used
category: "Storage" # Category to be used for searching catalog entries
maintainer: "Vincenzo Dell'Oste" # The maintainer of the catalog entry
license: "MIT" # The license
#projectURL: # A URL related to the catalog entry