version: '2'
.catalog:
	name: "NFS Storage" # Name of the versioned template of the Catalog Entry
	version: "0.1.0" # Version of the versioned template of the Catalog Entry
	description: |
		NFS Server based on alpine # Description of the versioned template of the Catalog Entry
		
services:
	nfs-server:
		scale: 1